src/models/Payment.py
from main import db


class Payment(db.Model):
    __tablename__ = "payments"

    id = db.Column(db.Integer, primary_key=True)
    full_amount_due = db.Column(db.Integer, nullable=False)
    upfront_amount_paid = db.Column(db.String, nullable=False)
    remainder_due = db.Column(db.Integer, nullable=False)

    booking_id = db.Column(db.Integer, db.ForeignKey("bookings.id"),
                           nullable=False)

src/controllers/auth_controller.py
from models.User import User
from main import db
from flask import Blueprint, request, abort, render_template, redirect, url_for
from main import bcrypt
from flask_login import login_user, logout_user, login_required
# from datetime import timedelta

auth = Blueprint('auth', __name__)


@auth.route("/", methods=["GET"])
def home_page():
    """
    Returns simple home page.
    """
    return render_template("home_page.html")


@auth.route("/auth/register", methods=["POST"])
def auth_register():
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()
    if user:
        return abort(400, description="user already exists")
    user = User()

    user.username = username
    user.password = bcrypt.generate_password_hash(password).decode("utf-8")

    db.session.add(user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route("/auth/login", methods=["POST"])
def auth_login():
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()
    # don't login if the user doesn't exist
    if not user:
        return abort(401, description="Incorrect username")
    if not bcrypt.check_password_hash(user.password, password):
        return abort(401, description="Incorrect password")

    login_user(user)
    return redirect(url_for('bookings.booking_index'))


@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')


@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')


@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.home_page'))

# @auth.route("/users", methods=["GET"])
# def users_index():
#     users = User.query.all()
#     return jsonify(users_schema.dump(users))

src/controllers/bookings_controller.py
from models.Booking import Booking
from models.Payment import Payment
from main import db
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_required
from datetime import date

bookings = Blueprint("bookings", __name__, url_prefix="/bookings")


@bookings.route("/", methods=["GET"])
@login_required
def booking_index():
    """
    Returns index of all bookings.
    """
    today = str(date.today())
    bookings = Booking.query.order_by(Booking.booking_date.asc()).all()
    payments = Payment.query.all()
    return render_template("bookings_index.html", bookings=bookings,
                           payments=payments, today=today)


@bookings.route("/<int:id>", methods=["POST", "GET"])
@login_required
def booking_show(id):
    """
    Show data for single booking using id.
    """
    booking = Booking.query.get(id)
    payment = Payment.query.filter_by(booking_id=id).first()
    return render_template("bookings_single.html", booking=booking,
                           payment=payment)


@bookings.route("/<int:id>/delete", methods=["GET", "DELETE"])
@login_required
def booking_delete(id):
    """
    Delete data for single booking using id.
    """
    booking = Booking.query.get(id)
    payment = Payment.query.filter_by(booking_id=id).first()
    if not booking:
        return "DELETED"
    db.session.delete(booking)
    db.session.delete(payment)
    db.session.commit()
    return redirect(url_for('bookings.booking_index'))


@bookings.route("/<int:id>/update", methods=["POST", "GET"])
@login_required
def booking_update(id):
    """
    Update booking using id.
    """
    if request.method == "POST":
        month = request.form.get("month")
        day = request.form.get("day")
        year = request.form.get("year")

        booking = Booking.query.filter_by(id=id).first()
        booking.first_name = request.form.get("first_name")
        booking.last_name = request.form.get("last_name")
        booking.phone = request.form.get("phone")
        booking.email = request.form.get("email")
        booking.num_participants = request.form.get("num_participants")
        booking.booking_date = f"{year}-{month}-{day}"
        booking.collection_time = request.form.get("collection_time")
        booking.return_time = request.form.get("return_time")

        if request.form.get("rental_complete") == "True":
            booking.rental_complete = True
        else:
            booking.rental_complete = False

        payment = Payment.query.filter_by(booking_id=id).first()
        payment.full_amount_due = float(request.form.get("full_amount_due"))

        if request.form.get("remainder_due_check") == "paid":
            payment.remainder_due = 0
        else:
            payment.remainder_due = request.form.get("remainder_due")

        db.session.commit()

        return redirect(url_for("bookings.booking_index"))

    booking = Booking.query.get(id)
    payment = Payment.query.filter_by(booking_id=id).first()
    booking_date = booking.booking_date.split("-")
    date = {"month": booking_date[1], "day": booking_date[2],
            "year": booking_date[0]}
    return render_template("booking_update.html", booking=booking,
                           payment=payment, date=date)

src/controllers/rent_controller.py
from models.Booking import Booking
from models.Payment import Payment
from main import db
from flask import Blueprint, request, render_template, redirect, url_for
from sqlalchemy import exists
from services.email_receipt import send_email

rent = Blueprint("rent", __name__, url_prefix="/rent")

# redirect from "/rent" to "/rent/payment" to "/rent/success"


def total_due(rt, ct, np):
    time = int(rt[:2]) - int(ct[:2])
    if time == 1:
        return str(20 * int(np))
    elif time == 2:
        return str(30 * int(np))
    elif time == 3:
        return str(40 * int(np))
    else:
        return str(70 * int(np))


@rent.route("/", methods=["POST", "GET"])
def booking_create():
    """
    Create a new booking.
    """
    if request.method == "POST":
        month = request.form.get("month")
        day = request.form.get("day")
        year = request.form.get("year")

        new_booking = Booking()
        new_booking.first_name = request.form.get("first_name")
        new_booking.last_name = request.form.get("last_name")
        new_booking.phone = request.form.get("phone")
        new_booking.email = request.form.get("email")
        new_booking.num_participants = request.form.get("num_participants")
        new_booking.booking_date = f"{year}-{month}-{day}"
        new_booking.collection_time = request.form.get("collection_time")
        new_booking.return_time = request.form.get("return_time")

        amt_due = total_due(new_booking.return_time,
                            new_booking.collection_time,
                            new_booking.num_participants)

        if len(new_booking.first_name
               ) != 0 and len(new_booking.last_name
                              ) != 0 and len(new_booking.email) != 0:

            db.session.add(new_booking)
            db.session.commit()

            return redirect(url_for("rent.booking_payment", amt_due=amt_due,
                                    id=new_booking.id))
    return render_template("rental_form.html")


@rent.route("/payment", methods=["POST", "GET"])
def booking_payment():
    amt_due = request.args.get("amt_due")
    id = request.args.get("id")
    booking = Booking.query.get(id)

    if request.method == "POST":
        new_payment = Payment()
        new_payment.full_amount_due = float(request.form.get(
                                            "full_amount_due"))
        new_payment.upfront_amount_paid = request.form.get(
            "upfront_amount_paid")

        if new_payment.upfront_amount_paid == "full":
            new_payment.remainder_due = 0
        elif new_payment.upfront_amount_paid == "deposit":
            new_payment.remainder_due = new_payment.full_amount_due - 50

        new_payment.booking_id = request.form.get("booking_id")

        (ret, ), = db.session.query(exists().where(
            Payment.booking_id == new_payment.booking_id))
        if not ret:
            db.session.add(new_payment)
            db.session.commit()

        return redirect(url_for("rent.booking_success"))

    return render_template("payment_form.html", amt_due=amt_due, id=id,
                           booking=booking)


@rent.route("/success", methods=["GET"])
def booking_success():
    booking = Booking.query.order_by(Booking.id.desc()).first()
    payment = Payment.query.filter_by(id=booking.id).first()
    send_email(booking, payment)
    return render_template("rent_success.html", booking=booking,
                           payment=payment)

src/templates/booking_update.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <h3>Update Booking</h3>
        <p>{{ date.month }}</p>
        <div>
            <form action="{{ url_for('bookings.booking_update', id=booking.id) }}" method="POST">
                <h4>PERSONAL DETAILS</h4>
                <div class="form-inline form-group">
                    <label for="exampleFormControlInput1">First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ booking.first_name }}" id="exampleFormControlInput1" placeholder="First Name">
                    <label for="exampleFormControlInput1">Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ booking.last_name }}" id="exampleFormControlInput1" placeholder="Last Name">
                </div>
                <div class="form-inline form-group">  
                    <label for="exampleFormControlInput1">Email Address</label>
                    <input type="email" class="form-control" name="email" value="{{ booking.email }}" id="exampleFormControlInput1" placeholder="name@example.com">
                    <label for="exampleFormControlInput1">Phone Number</label>
                    <input type="text" class="form-control" name="phone" value="{{ booking.phone }}" id="exampleFormControlInput1" placeholder="00 000 00000">
                </div>
                
                <h4>BOOKING DETAILS</h4>
                <div class="form-inline form-group">
                    <label for="exampleFormControlSelect1">Number Of Participants</label>
                    <input type="text" class="form-control" name="num_participants" value="{{ booking.num_participants }}" id="exampleFormControlInput1">
                </div>
                    
                <div class="form-inline form-group">
                    <label for="exampleFormControlSelect1">Month</label>
                    <input type="text" class="form-control" name="month" value="{{date.month}}" id="exampleFormControlSelect1">
                    <label for="exampleFormControlSelect1">Day</label>
                    <input type="text" class="form-control" name="day" value="{{date.day}}" id="exampleFormControlSelect1">
                    <label for="exampleFormControlSelect1">Year</label>
                    <input type="text" class="form-control" name="year" value="{{date.year}}" id="exampleFormControlSelect1">
                </div>                
                
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Collection Time</label>
                    <select class="form-control" name="collection_time" value="{{ booking.collection_time }}" id="exampleFormControlSelect1">
                        {% for i in range(8, 10) %}
                        <option>0{{i}}:00</option>
                        {% endfor %}
                        {% for i in range(10, 19) %}
                        <option>{{i}}:00</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Return Time</label>
                    <select class="form-control" name="return_time" value="{{ booking.return_time }}" id="exampleFormControlSelect1">
                        {% for i in range(9, 10) %}
                        <option>0{{i}}:00</option>
                        {% endfor %}
                        {% for i in range(10, 19) %}
                        <option>{{i}}:00</option>
                        {% endfor %}
                    </select>
                </div>

                <h4>PAYMENT DETAILS</h4>
                <label for="full_amt_due">Full Amount Due (AU$)</label>
                <input type="text" name="full_amount_due" id="full_amt_due" value="{{ payment.full_amount_due }}" readonly>
                <div class="form-check form-inline">
                    <input class="form-check-input" type="radio" name="remainder_due_check" id="flexRadioDefault1" value="paid">
                    <label class="form-check-label" for="flexRadioDefault1">
                      Paid
                    </label>
                  </div>
                  <div class="form-check form-inline">
                    <input class="form-check-input" type="radio" name="remainder_due_check" id="flexRadioDefault2"  checked>
                    <label class="form-check-label" for="flexRadioDefault2">
                      Money Due 
                    </label>
                    <input type="text" name="remainder_due" value="{{ payment.remainder_due }}" placeholder="Money Due">
                  </div>
                

                <h4>BOOKING STATUS</h4>
                <div class="form-check form-inline">
                    <input class="form-check-input" type="radio" name="rental_complete" value="True" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1">
                      Rental Complete
                    </label>
                  </div>
                  <div class="form-check form-inline">
                    <input class="form-check-input" type="radio" name="rental_complete" value="False" id="flexRadioDefault2" checked>
                    <label class="form-check-label" for="flexRadioDefault2">
                      Rental Not Complete
                    </label>
                  </div>
            
                  <a href="bookings_index.html"><button>Cancel</button></a> <button type="submit" class="btn btn-primary">Update</button>
        </form>
        </div>
    </div>
    <br/>
{% endblock %}

src/templates/bookings_index.html
{% extends "layout.html" %}

{% block content%}        
<br/>
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th scope="col">Ref.</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Email</th>
            <th scope="col">Riders</th>
            <th scope="col">Date</th>
            <th scope="col">OutTime</th>
            <th scope="col">InTime</th>
            <th scope="col">$$$</th>
            <th scope="col">Paid</th>            
        </tr>
    </thead>
    <tbody>
        {% for booking in bookings %}
        {% if booking.booking_date >= today and booking.rental_complete == False %}
            {% if booking.booking_date == today %}
            <tr class="clickable text-center table-warning" onclick="window.location='/bookings/{{booking.id}}'">
                <th scope="row">{{booking.id}}</th>
                <td>{{booking.first_name}} {{booking.last_name}}</td>
                <td>{{booking.phone}}</td>
                <td>{{booking.email}}</td>
                <td>{{booking.num_participants}}</td>
                <td>{{booking.booking_date}}</td>
                <td>{{booking.collection_time}}</td>
                <td>{{booking.return_time}}</td>
                {% for payment in payments %}
                    {% if payment.booking_id == booking.id %}
                        <td>${{payment.full_amount_due}}</td>
                        {% if payment.remainder_due == 0 %}
                        <td><span>&#10003;</span></td>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </tr>
            {% else %}
            <tr class="clickable text-center" onclick="window.location='/bookings/{{booking.id}}'">
                <th scope="row">{{booking.id}}</th>
                <td>{{booking.first_name}} {{booking.last_name}}</td>
                <td>{{booking.phone}}</td>
                <td>{{booking.email}}</td>
                <td>{{booking.num_participants}}</td>
                <td>{{booking.booking_date}}</td>
                <td>{{booking.collection_time}}</td>
                <td>{{booking.return_time}}</td>
                {% for payment in payments %}
                    {% if payment.booking_id == booking.id %}
                        <td>${{payment.full_amount_due}}</td>
                        {% if payment.remainder_due == 0 %}
                        <td><span>&#10003;</span></td>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </tr>
            {% endif%}
        {% endif %}
        {% endfor %}
    </tbody>
</table>
<br/>
<br/>
<h3>Archive</h3>
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th scope="col">Ref.</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">Email</th>
            <th scope="col">Riders</th>
            <th scope="col">Date</th>
            <th scope="col">OutTime</th>
            <th scope="col">InTime</th>
            <th scope="col">$$$</th>
            <th scope="col">Paid</th>            
        </tr>
    </thead>
    <tbody>
        {% for booking in bookings %}
        {% if booking.booking_date < today or booking.rental_complete == True %}
            {% if booking.rental_complete != True %}
            <tr class="clickable text-center table-danger" onclick="window.location='/bookings/{{booking.id}}'"><a href=""></a>
                <th scope="row">{{booking.id}}</th>
                <td>{{booking.first_name}} {{booking.last_name}}</td>
                <td>{{booking.phone}}</td>
                <td>{{booking.email}}</td>
                <td>{{booking.num_participants}}</td>
                <td>{{booking.booking_date}}</td>
                <td>{{booking.collection_time}}</td>
                <td>{{booking.return_time}}</td>
                {% for payment in payments %}
                    {% if payment.booking_id == booking.id %}
                        <td>${{payment.full_amount_due}}</td>
                        {% if payment.remainder_due == 0 %}
                        <td><span>&#10003;</span></td>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </tr>
            {% else %}
            <tr class="clickable text-center" onclick="window.location='/bookings/{{booking.id}}'"><a href=""></a>
                <th scope="row">{{booking.id}}</th>
                <td>{{booking.first_name}} {{booking.last_name}}</td>
                <td>{{booking.phone}}</td>
                <td>{{booking.email}}</td>
                <td>{{booking.num_participants}}</td>
                <td>{{booking.booking_date}}</td>
                <td>{{booking.collection_time}}</td>
                <td>{{booking.return_time}}</td>
                {% for payment in payments %}
                    {% if payment.booking_id == booking.id %}
                        <td>${{payment.full_amount_due}}</td>
                        {% if payment.remainder_due == 0 %}
                        <td><span>&#10003;</span></td>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </tr>            
            {% endif %}
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

src/templates/bookings_single.html
{% extends "layout.html" %}

{% block content %}

<br/>

<h3>REFERENCE: {{booking.id}}</h3>

<h3>PERSONAL DETAILS</h3>
    <p>Name: {{booking.first_name}} {{booking.last_name}}</p>
    <p>Phone: {{booking.phone}}</p>
    <p>Email: {{booking.email}}</p>

<h3>BOOKING DETAILS</h3>
    <p>Num. Participants: {{booking.num_participants}}</p>
    <p>Date: {{booking.booking_date}}</p>
    <p>Collection Time: {{booking.collection_time}}</p>
    <p>Return Time: {{booking.return_time}}</p>

<h3>PAYMENT DETAILS</h3>
    <p>Full Amount Due: ${{payment.full_amount_due}}.00</p>
    <p>Upfront Amount Paid: {{payment.upfront_amount_paid}}</p>
    <p>Remainder Due: ${{payment.remainder_due}}.00</p>

<h3>BOOKING STATUS</h3>
    {% if booking.rental_complete == False %}
    <!-- x mark -->
    <p>Rental Complete: &#10005;</p>
    {% else %}
    <!-- check mark -->
    <p>Rental Complete: &#10003;</p> 
    {% endif %}


<a href="/bookings/">Back</a>
<a href="{{ url_for('bookings.booking_update', id=booking.id) }}"><button>Update Booking</button></a>
<a href="{{ url_for('bookings.booking_delete', id=booking.id) }}"><button>Delete Booking</button></a>
<br/>
<br/>

{% endblock %}

src/templates/home_page.html
{% extends "layout.html" %}

{% block content %}

    <br><br><br><br><br><br>
    <h1>ISLAND BIKE RENTALS</h1>
    <h2>Rent A Bike</h2>
    <a href="/rent"><h4>RENT</h4></a>
    <br><br>
    <h3>Rental Prices</h3>
    <p>&emsp;1 hour -- $20</p>
    <p>&emsp;2 hours -- $30</p>
    <p>&emsp;3 hours -- $40</p>
    <p>&emsp;Full Day -- $70</p>
    <p>**prices are per person</p>

{% endblock %}

src/templates/layout.html
<!doctype html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <head>
        <title> Island Bike Rentals </title>
    </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Island Bike Rentals</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/rent">RENT</a>
          </div>
        </div>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ADMIN
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="/login">Login</a>
              <!-- <a class="dropdown-item" href="/signup">Register</a> -->
              <a class="dropdown-item" href="/bookings">Bookings</a>
              <a class="dropdown-item" href="/logout">Logout</a>
            </div>
          </div>
        <!-- <div class="navbar-nav">
            <button class="btn nav-link nav-item" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <a class="nav-item nav-link" href="/login">LOGIN</a>
            <a class="nav-item nav-link" href="/signup">Register</a>
            <a class="nav-item nav-link" href="/logout">Log out</a>
        </div> -->
    </nav>

    <body>
        <div class="container">
        {% block content %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% endblock %}
        </div>
    </body>
</html>

src/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <br/>
        <h3>Log in</h3>
        <div>
            <form action="{{ url_for('auth.auth_login') }}" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" name="username" nameid="exampleInputEmail1" placeholder="Enter Username">
                </div>
                 <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>

            </form>
        </div>
        <br/>
        <a href="home_page.html"><button>Cancel</button></a>
    </div>
{% endblock %}

src/templates/rental_form.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <br/>
        <h3>RENT A BIKE!</h3>
        <br/>
        <div>
            <form action="{{ url_for('rent.booking_create') }}" method="POST">

                <div class="form-inline form-group">
                    <label for="exampleFormControlInput1">First Name</label>
                    <input type="text" class="form-control" name="first_name" id="exampleFormControlInput1" placeholder="First Name">
                    <label for="exampleFormControlInput1">Last Name</label>
                    <input type="text" class="form-control" name="last_name" id="exampleFormControlInput1" placeholder="Last Name">
                </div>
                <div class="form-inline form-group">  
                    <label for="exampleFormControlInput1">Email Address</label>
                    <input type="email" class="form-control" name="email" id="exampleFormControlInput1" placeholder="name@example.com">
                    <label for="exampleFormControlInput1">Phone Number</label>
                    <input type="text" class="form-control" name="phone" id="exampleFormControlInput1" placeholder="00 000 00000">
                </div>
                    
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Number Of Participants</label>
                    <select class="form-control" name="num_participants" id="exampleFormControlSelect1">
                        {% for i in range(1, 11) %}
                        <option>{{i}}</option>
                        {% endfor %}
                    </select>
                </div>
                    
                <div class="form-inline form-group">
                    <label for="exampleFormControlSelect1">Month</label>
                    <select class="form-control" name="month" id="exampleFormControlSelect1">
                        {% for i in range(1, 10) %}
                        <option>0{{i}}</option>
                        {% endfor %}
                        {% for i in range(10, 13) %}
                        <option>{{i}}</option>
                        {% endfor %}
                    </select>
                    <label for="exampleFormControlSelect1">Day</label>
                    <select class="form-control" name="day" id="exampleFormControlSelect1">
                        {% for i in range(1, 10) %}
                        <option>0{{i}}</option>
                        {% endfor %}
                        {% for i in range(10, 32) %}
                        <option>{{i}}</option>
                        {% endfor %}
                    </select>
                    <label for="exampleFormControlSelect1">Year</label>
                    <select class="form-control" name="year" id="exampleFormControlSelect1">
                        <option>2021</option>
                    </select>
                </div>                
                  
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Collection Time</label>
                    <select class="form-control" name="collection_time" id="exampleFormControlSelect1">
                        {% for i in range(8, 10) %}
                        <option>0{{i}}:00</option>
                        {% endfor %}
                        {% for i in range(10, 19) %}
                        <option>{{i}}:00</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Return Time</label>
                    <select class="form-control" name="return_time" id="exampleFormControlSelect1">
                        {% for i in range(9, 10) %}
                        <option>0{{i}}:00</option>
                        {% endfor %}
                        {% for i in range(10, 19) %}
                        <option>{{i}}:00</option>
                        {% endfor %}
                    </select>
                </div>
                
                <a href="/" id="cancel" name="cancel" class="btn btn-default">Cancel</a><button type="submit" class="btn btn-primary">Continue To Payment</button>
            </form>
            <br/>
            
        </div>
    </div>
{% endblock %}

src/templates/signup.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <br/>
        <h3>Register</h3>
        <div>
            <form action="{{ url_for('auth.auth_register') }}" method="POST">
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" name="username" nameid="exampleInputEmail1" placeholder="Enter Username">
                </div>
                 <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <br/>
        <a href="/"><button>Cancel</button></a>
    </div>
{% endblock %}